"""
PyTorch Dataset and DataLoader abstractions for Khmer legal retrieval.

Provides datasets for:
1. LegalPairsDataset: (query, passage) pairs for bi-encoder training and validation.
2. CorpusDataset: Full 1,976-article corpus for full-rank retrieval evaluation.
3. QABenchmarkDataset: 200 human-verified benchmark questions (T-Q).
"""

import json
from pathlib import Path
from typing import Any, Optional

import torch
from torch.utils.data import DataLoader, Dataset

from src.config.logging import get_logger, setup_logging
from src.dl.seed import DEFAULT_SEED
from src.dl.text import normalize_khmer_text

setup_logging()
logger = get_logger(__name__)


def generate_doc_id(law_name: str, article_number: int) -> str:
    """Generate standardized document identifier.

    Args:
        law_name: Law name ('Civil Code 2007' or 'Criminal Code 2009').
        article_number: Article integer number.

    Returns:
        Standardized identifier string like 'civil_code_kh_art_1'.
    """
    if "Civil" in law_name:
        prefix = "civil_code_kh"
    elif "Criminal" in law_name:
        prefix = "criminal_code_kh"
    else:
        prefix = law_name.lower().replace(" ", "_")
    return f"{prefix}_art_{article_number}"


class LegalPairsDataset(Dataset):
    """PyTorch Dataset loading (query, passage) training or validation pairs.

    Loads from JSONL split files generated by `src.dl.prepare_splits`.
    """

    def __init__(
        self,
        jsonl_path: Path | str,
        normalize_text: bool = True,
        vocab: Optional[Any] = None,
        max_seq_len: int = 256,
    ) -> None:
        """Initialize the dataset.

        Args:
            jsonl_path: Path to the split JSONL file (train.jsonl, val.jsonl, etc.).
            normalize_text: Whether to apply NFC and zero-width space normalization.
            vocab: Optional KhmerVocab instance to pre-encode text into integer tensors.
            max_seq_len: Maximum sequence length for pre-encoded tensors.
        """
        self.path = Path(jsonl_path)
        if not self.path.exists():
            raise FileNotFoundError(f"Split file not found: {self.path}")

        self.normalize_text = normalize_text
        self.vocab = vocab
        self.max_seq_len = max_seq_len
        self.records: list[dict[str, Any]] = []

        with open(self.path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                item = json.loads(line)
                if self.normalize_text:
                    item["query"] = normalize_khmer_text(item["query"])
                    item["passage"] = normalize_khmer_text(item["passage"])
                self.records.append(item)

        if self.vocab is not None:
            logger.info(f"Pre-encoding {len(self.records)} pairs with vocabulary for rapid batching...")
            for item in self.records:
                q_ids, q_mask = self.vocab.encode(item["query"], max_seq_len=self.max_seq_len)
                p_ids, p_mask = self.vocab.encode(item["passage"], max_seq_len=self.max_seq_len)
                item["query_ids"] = torch.tensor(q_ids, dtype=torch.long)
                item["query_mask"] = torch.tensor(q_mask, dtype=torch.float32)
                item["passage_ids"] = torch.tensor(p_ids, dtype=torch.long)
                item["passage_mask"] = torch.tensor(p_mask, dtype=torch.float32)

        logger.info(f"Loaded {len(self.records)} pairs from {self.path.name}")

    def __len__(self) -> int:
        return len(self.records)

    def __getitem__(self, idx: int) -> dict[str, Any]:
        item = self.records[idx]
        record = {
            "id": item["id"],
            "query": item["query"],
            "passage": item["passage"],
            "doc_id": item["doc_id"],
            "law_name": item["law_name"],
            "article_number": item["article_number"],
            "title": item.get("title", ""),
        }
        if "query_ids" in item:
            record["query_ids"] = item["query_ids"]
            record["query_mask"] = item["query_mask"]
            record["passage_ids"] = item["passage_ids"]
            record["passage_mask"] = item["passage_mask"]
        return record


class CorpusDataset(Dataset):
    """PyTorch Dataset loading the full 1,976-article Khmer legal corpus.

    Supports indexing by integer position and fast lookup by document ID.
    """

    def __init__(
        self,
        corpus_path: Path | str = Path("data/05_splits/corpus.jsonl"),
        normalize_text: bool = True,
    ) -> None:
        """Initialize the corpus dataset.

        Args:
            corpus_path: Path to corpus.jsonl.
            normalize_text: Whether to apply Unicode NFC and artifact cleaning.
        """
        self.path = Path(corpus_path)
        if not self.path.exists():
            raise FileNotFoundError(f"Corpus file not found: {self.path}")

        self.normalize_text = normalize_text
        self.records: list[dict[str, Any]] = []
        self._doc_id_to_idx: dict[str, int] = {}

        with open(self.path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                item = json.loads(line)
                if self.normalize_text:
                    item["text"] = normalize_khmer_text(item["text"])
                    item["text_without_title"] = normalize_khmer_text(item["text_without_title"])
                    if "content_with_context" in item:
                        item["content_with_context"] = normalize_khmer_text(
                            item["content_with_context"]
                        )
                doc_id = item["doc_id"]
                self._doc_id_to_idx[doc_id] = len(self.records)
                self.records.append(item)

        logger.info(f"Loaded full corpus of {len(self.records)} articles from {self.path.name}")

    def __len__(self) -> int:
        return len(self.records)

    def __getitem__(self, idx: int) -> dict[str, Any]:
        return self.records[idx]

    def get_by_doc_id(self, doc_id: str) -> dict[str, Any]:
        """Lookup an article record by its unique doc_id."""
        if doc_id not in self._doc_id_to_idx:
            raise KeyError(f"Document ID '{doc_id}' not in corpus")
        return self.records[self._doc_id_to_idx[doc_id]]

    @property
    def doc_ids(self) -> list[str]:
        """List of all document IDs in the corpus in sequential order."""
        return [r["doc_id"] for r in self.records]

    def get_texts(
        self,
        use_context: bool = False,
        strip_title: bool = False,
    ) -> list[str]:
        """Return full list of passage strings for embedding all articles.

        Args:
            use_context: If True, uses content_with_context (hierarchical prefixes).
            strip_title: If True, uses text_without_title instead of text.

        Returns:
            List of 1,976 passage strings in corpus order.
        """
        if use_context:
            return [r.get("content_with_context", r["text"]) for r in self.records]
        if strip_title:
            return [r["text_without_title"] for r in self.records]
        return [r["text"] for r in self.records]


class QABenchmarkDataset:
    """Loader for the 200 human-verified benchmark questions (T-Q)."""

    def __init__(
        self,
        qa_path: Path | str = Path("tests/evaluation/ground_truth_qa_kh.json"),
        normalize_text: bool = True,
    ) -> None:
        """Initialize the QA benchmark dataset.

        Args:
            qa_path: Path to ground_truth_qa_kh.json.
            normalize_text: Whether to apply Unicode normalization to questions.
        """
        self.path = Path(qa_path)
        if not self.path.exists():
            raise FileNotFoundError(f"QA benchmark file not found: {self.path}")

        with open(self.path, "r", encoding="utf-8") as f:
            raw_data = json.load(f)

        self.records: list[dict[str, Any]] = []
        for item in raw_data:
            law_name = item.get("expected_law", "")
            articles = item.get("expected_articles", [])
            expected_doc_ids = [generate_doc_id(law_name, int(a)) for a in articles]

            q_text = item.get("question_kh", "")
            if normalize_text:
                q_text = normalize_khmer_text(q_text)

            self.records.append({
                "id": item.get("id", ""),
                "question": q_text,
                "expected_law": law_name,
                "expected_articles": [int(a) for a in articles],
                "expected_doc_ids": expected_doc_ids,
                "chapter_hint": item.get("chapter_hint"),
                "verifier": item.get("verifier", "unverified"),
            })

        logger.info(f"Loaded {len(self.records)} benchmark questions from {self.path.name}")

    def __len__(self) -> int:
        return len(self.records)

    def __getitem__(self, idx: int) -> dict[str, Any]:
        return self.records[idx]

    @property
    def questions(self) -> list[str]:
        """List of all question strings."""
        return [r["question"] for r in self.records]

    @property
    def ground_truth_doc_ids(self) -> list[set[str]]:
        """List of sets of expected doc_ids for each question."""
        return [set(r["expected_doc_ids"]) for r in self.records]


def collate_pairs(batch: list[dict[str, Any]]) -> dict[str, Any]:
    """Collator function for LegalPairsDataset DataLoader batches.

    Args:
        batch: List of dictionaries from LegalPairsDataset[idx].

    Returns:
        Batched dictionary containing lists of queries, passages, metadata,
        and optionally stacked token ID and mask tensors.
    """
    res = {
        "ids": [item["id"] for item in batch],
        "queries": [item["query"] for item in batch],
        "passages": [item["passage"] for item in batch],
        "doc_ids": [item["doc_id"] for item in batch],
        "law_names": [item["law_name"] for item in batch],
        "article_numbers": [item["article_number"] for item in batch],
    }
    if batch and "query_ids" in batch[0]:
        res["query_ids"] = torch.stack([item["query_ids"] for item in batch])
        res["query_mask"] = torch.stack([item["query_mask"] for item in batch])
        res["passage_ids"] = torch.stack([item["passage_ids"] for item in batch])
        res["passage_mask"] = torch.stack([item["passage_mask"] for item in batch])
    return res


def create_dataloader(
    dataset: Dataset,
    batch_size: int = 32,
    shuffle: bool = True,
    drop_last: bool = False,
    num_workers: int = 0,
) -> DataLoader:
    """Create a configured DataLoader for training or evaluation.

    Args:
        dataset: PyTorch Dataset instance.
        batch_size: Number of items per batch.
        shuffle: Whether to shuffle items.
        drop_last: Whether to drop the last incomplete batch.
        num_workers: Number of background subprocesses for loading.

    Returns:
        Configured torch.utils.data.DataLoader instance.
    """
    return DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        drop_last=drop_last,
        num_workers=num_workers,
        collate_fn=collate_pairs if isinstance(dataset, LegalPairsDataset) else None,
    )
